services:

  app-prod:
    container_name: document-autofill-backend
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    env_file: .env
    environment:
      DB__POSTGRES__HOST: db
      DB__POSTGRES__PORT: 5432
    ports:
      - "${SERVER__PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  db:
    container_name: document-autofill-database
    image: postgres:18
    environment:
      POSTGRES_USER: $DB__POSTGRES__USER
      POSTGRES_PASSWORD: $DB__POSTGRES__PASSWORD
      POSTGRES_DB: $DB__POSTGRES__DBNAME
    ports:
      - "$DB__POSTGRES__PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      start_period: 30s
      start_interval: 5s
      interval: 5m
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
